name: CreeperCharger
version: '1.5'
main: com.ashkiano.creepercharger.CreeperCharger
api-version: '1.16'
author: AshKiano
commands:
  getcharger:
    description: Get the Creeper Charging Stick
    usage: /<command>